---
- name: Get certificate file stat.
  with_items: "{{ cert_item.domains }}"
  loop_control:
    loop_var: domain
  stat:
    path: /etc/letsencrypt/live/{{ domain | replace('*.', '') }}/cert.pem
  register: letsencrypt_cert_stat

- name: Set certificate already exists fact.
  set_fact:
    letsencrypt_any_file_need_create: "{{
        letsencrypt_cert_stat.results
      | map(attribute='stat')
      | map(attribute='exists')
      | reject
      | list
      | length
      > 0
    }}"

- name: Stop services to allow certbot to generate a cert.
  service:
    name: "{{ item }}"
    state: stopped
  when: letsencrypt_any_file_need_create
  with_items: "{{ certbot_create_standalone_stop_services }}"

- name: Generate new certificate if one doesn't exist.
  shell: "{{ certbot_create_command }}"
  when: letsencrypt_any_file_need_create
  tags:
    # disable Ansible Lint for rule
    # [305] Use shell only when shell functionality is required
    - skip_ansible_lint

- name: Start services after cert has been generated.
  service:
    name: "{{ item }}"
    state: started
  when: letsencrypt_any_file_need_create
  with_items: "{{ certbot_create_standalone_stop_services }}"
